export const emojiData = [
    { name: "grinning face with smiling eyes", emojicode: "😄" },
    { name: "grinning face", emojicode: "😃" },
    { name: "smiling face with hearts", emojicode: "🥰" },
    { name: "smirking face", emojicode: "😏" },
    { name: "sneezing face", emojicode: "🤧" },
    { name: "loudly crying face", emojicode: "😭" },
    { name: "start struck", emojicode: "🤩" },
    { name: "face with tongue", emojicode: "😛" },
    { name: "squinting face with tongue", emojicode: "😝" },
    { name: "winking face with tongue", emojicode: "😜" },
    { name: "smiling face with sunglasses", emojicode: "😎" },
    { name: "downcast face with sweat", emojicode: "😓" },
    { name: "grinning face with sweat", emojicode: "😅" },
    { name: "thinking", emojicode: "🤔" },
    { name: "tired face", emojicode: "😫" },
    { name: "triumph", emojicode: "😤" },
    { name: "unamused", emojicode: "😒" },
    { name: "upside down face", emojicode: "🙃" },
    { name: "vomiting face", emojicode: "🤮" },
    { name: "weary face", emojicode: "😩" },
    { name: "wink", emojicode: "😉" },
    { name: "woozy face", emojicode: "🥴" },
    { name: "worried face", emojicode: "😟" },
    { name: "yawning face", emojicode: "🥱" },
    { name: "yum", emojicode: "😋" },
    { name: "zany face", emojicode: "🤪" },
    { name: "zipper mouth face", emojicode: "🤐" },
    { name: "thumbs up", emojicode: "👍" },
    { name: "thumbs down", emojicode: "👎" },
    { name: "100", emojicode: "💯" }
]